markdown: kramdown
highlighter: rouge
relative_permalinks: false

repository: https://github.com/qiujuer/Genius-Android
help_url: https://github.com/qiujuer/Genius-Android

collections:
  docs:
    output: true

kramdown:
    syntax_highlighter: coderay